2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Configure stats pid to 29544
2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Loading settings from /Users/aliramlaoui/.config/wandb/settings
2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Loading settings from /Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/wandb/settings
2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-23 19:51:17,495 INFO    MainThread:29544 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/main.py', 'program_abspath': '/Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/src/main.py', 'program': '/Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/src/main.py'}
2023-11-23 19:51:17,496 INFO    MainThread:29544 [wandb_init.py:_log_setup():524] Logging user logs to /Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/wandb/run-20231123_195117-yxif8ojd/logs/debug.log
2023-11-23 19:51:17,496 INFO    MainThread:29544 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/wandb/run-20231123_195117-yxif8ojd/logs/debug-internal.log
2023-11-23 19:51:17,496 INFO    MainThread:29544 [wandb_init.py:init():564] calling init triggers
2023-11-23 19:51:17,496 INFO    MainThread:29544 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'n_epochs': 50, 'batch_size': 4, 'n_layers': 3, 'lr': 0.0001, 'weight_decay': 0.0001}
2023-11-23 19:51:17,496 INFO    MainThread:29544 [wandb_init.py:init():614] starting backend
2023-11-23 19:51:17,496 INFO    MainThread:29544 [wandb_init.py:init():618] setting up manager
2023-11-23 19:51:17,497 INFO    MainThread:29544 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-11-23 19:51:17,498 INFO    MainThread:29544 [wandb_init.py:init():624] backend started and connected
2023-11-23 19:51:17,499 INFO    MainThread:29544 [wandb_init.py:init():716] updated telemetry
2023-11-23 19:51:17,513 INFO    MainThread:29544 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-23 19:51:17,947 INFO    MainThread:29544 [wandb_run.py:_on_init():2254] communicating current version
2023-11-23 19:51:17,983 INFO    MainThread:29544 [wandb_run.py:_on_init():2263] got version response 
2023-11-23 19:51:17,983 INFO    MainThread:29544 [wandb_init.py:init():800] starting run threads in backend
2023-11-23 19:51:18,020 INFO    MainThread:29544 [wandb_run.py:_console_start():2233] atexit reg
2023-11-23 19:51:18,020 INFO    MainThread:29544 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-11-23 19:51:18,020 INFO    MainThread:29544 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-11-23 19:51:18,020 INFO    MainThread:29544 [wandb_run.py:_redirect():2178] Redirects installed.
2023-11-23 19:51:18,021 INFO    MainThread:29544 [wandb_init.py:init():841] run started, returning control to user process
2023-11-23 19:51:19,466 ERROR   MainThread:29544 [util.py:get_module():267] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "/Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/venv/lib/python3.10/site-packages/wandb/util.py", line 233, in import_module_lazy
    return sys.modules[name]
KeyError: 'plotly.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/venv/lib/python3.10/site-packages/wandb/util.py", line 262, in get_module
    return import_module_lazy(name)
  File "/Users/aliramlaoui/Library/CloudStorage/GoogleDrive-ramlaouiali@gmail.com/My Drive/Cours 3A/AST/project/unrolled-nn-restoration/venv/lib/python3.10/site-packages/wandb/util.py", line 235, in import_module_lazy
    spec = importlib.util.find_spec(name)
  File "/Users/aliramlaoui/anaconda3/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'plotly'
2023-11-23 19:51:26,096 WARNING MsgRouterThr:29544 [router.py:message_loop():77] message_loop has been closed
